### ISSUE TITLE
Web interface

### ISSUE THREAD

**Issue by gordonpn** [gordonpn/web-career-portal-clone#6]
# 3 dashboards:

## User dashboard

* [x] Should be able to sign up as a user. #10
* [x] Three user categories should be provided:
    * [x] Basic: Employee can only view jobs but cannot apply. No charge
    * [x] Prime: Employee can view jobs as well as apply for up to five jobs. A monthly charge of $10 will be applied.
    * [x] Gold: Employee can view and apply to as many jobs as he/she wants. A monthly charge of $20 will be applied.
* [x] Should be able to choose categories. #11
* [x] Users have the ability to upgrade or downgrade their category. Charges should be updated based on the new category. #11
* [x] When users upgrade their category, it should update the user category status. #11
* [x] Should have a user login and a mechanism to verify credentials or forgot password. #9 
* [x] Should be able to search for jobs. #35 
* [x] Should be able to search by job category. #36
* [x] Should be able to apply for jobs. #38
* [x] Should be able to maintain status of applied jobs. #39
* [x] Should be able to delete user profile. #14
* [x] Should be able to update user profile details. #37 #50
* [x] Should be able to withdraw from an applied job. #38

## Employer dashboard

* [x] Should have an admin login and a mechanism to verify credentials or forgot password. #9 
* [ ] Should be able to maintain new users and update the user table.
* [x] Should be able to post jobs. #49
* [x] Should be able to maintain current jobs and categories. #54 
* [x] Should be able to maintain status of posted jobs. #51
* [x] Should be able to see a summary of current application at a glance. #52
* [x] Two user categories should be provided:
    * [x] Prime: Employer can post up to five jobs. A monthly charge of $50 will be applied.
    * [x] Gold: Employer can post as many jobs as he/she wants. A monthly charge of $100 will be applied.
* [x] Users have the ability to upgrade or downgrade their category. Charges should be updated based on the new category. #11
* [x] When users upgrade their category, it should update the user category status. #11
* [x] Employer dashboard should have a contact us section to help user with contact information/helpline. #35 #50

## Admin dashboard

* [x] Should have an admin login and a mechanism to verify credentials or forgot
password. #9 
* [x] Should be able to activate or deactivate a user. #29
* [x] Should be able to see all activities in the system. #30 

# More Details

* [x] All Users must have the ability to provide a method of payment to their account and provide the needed information to be charged. #16
* [x] Method of payments could be either credit card charge or authorization from an existing checking account. #17
    * [x] In each case the proper information for withdrawal must be supplied by the user. #13 
* [x] The user has the option to choose between an automatic withdrawal or manual withdrawal. #13 
* [x] An automatic withdrawal is done automatically by the system at the beginning of each month by applying a charge to the user from a preselected method of payment. #44 
* [x] Users can have many methods of payments associated with their accounts and should be able to add/remove or edit their methods of payments. #16
* [x] An account that is negative will be frozen until it is settled and a payment is made. #12
* [x] The user of a frozen account will be able to login to the system but will not be able to access the services provided by the dashboard until the user account is settled. #12
* [x] When a charge is applied to an account, an automatic email is sent to the user informing of the charge and account status. #18
* [x] A suffering account will receive a warning message once a week until the account is settled or deactivated. #41 
* [x] A suffering account for a year will be deactivated automatically by the system. #41 
* [x] All users must have access to different reports that will enable them to obtain any needed information whether related to their account, posted jobs, applied jobs, accepted jobs, history, etc. #48
